### ISSUE TITLE
obtain the scala-compiler (et al) jars for scala itself

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#240]
we currently don't attempt to resolve scala-compiler (et al) if the organization matches the scalaOrganization, to avoid cycles.

But this means that scala developers cannot use the ensime assembly jars or scala repl. It would be good to resolve the scala-compiler jars (even if it's a local `ensime-sbt` hack) to remove this restriction.

**Comment by fommil** [comment]
the part of the code that is relevant is https://github.com/ensime/ensime-sbt/blob/v1.11.0/src/main/scala/EnsimePlugin.scala#L168-L177

**Comment by fommil** [comment]
from paulp https://github.com/paulp/policy/blob/master/project/PolicyBuild.scala and https://github.com/paulp/psp-libsbt/tree/master/libsbt/src/main/scala

**Comment by fommil** [comment]
I thought of an evil hack... make the ivys empty but then transform the EnsimeConfig to point to hard coded jar files, assuming everything gets downloaded into the ivy folder. At that point you can access the scala version.

**Comment by fommil** [comment]
@szeiger are you aware of an way to obtain the STARR jars in the scala sbt build?

**Comment by szeiger** [comment]
STARR is resolved as a normal Scala dependency through Ivy. You can get the locations of the JARs from the `scalaInstance`: https://github.com/scala/scala/blob/2.12.x/build.sbt#L106

**Comment by fommil** [comment]
Interesting. We may need to refactor to support this, because currently we expect a list of ivy configs.

This scalaInstance trick might not work for `scalap`, which we also have to resolve. Hmm.

**Comment by szeiger** [comment]
You can look at `bootstrap/scalaOrganization` and `bootstrap/scalaVersion` if you want to resolve the dependencies on your own. I would assume that sbt internally builds an Ivy config from these settings but I haven't checked any further. These values are also valid for `scalap` because it is built as part of the core Scala repo.

Versions of other modules will be available from the compiler JAR in 2.12.x (see https://github.com/scala/scala/pull/5379). In earlier versions this knowledge is not preserved in the artifacts, so you cannot reliably resolve the correct module versions for an arbitrary Scala build.

**Comment by fommil** [comment]
I think ivy is still getting into a circular dependency even with manually entered scala versions :confounded:

**Comment by szeiger** [comment]
On which project are you setting it? Take a look at https://github.com/sbt/sbt/issues/1872. This is why we're going through the separate `bootstrap` project.

**Comment by fommil** [comment]
we have to define it on all projects because of the way ivy works, not `in ThisBuild`

https://github.com/ensime/ensime-sbt/blob/2.0/src/main/scala/EnsimePlugin.scala#L152-L163

if there was a canonical way to add it just to the root project, that would be enough for our purposes. I should experiment with setting it on `ThisBuild`

**Comment by fommil** [comment]
yeah if that block is moved to build settings we get failures because the ivyConfigurations are not defined there

```
[info] [error]   {.}/*:ivyConfigurations from {.}/*:ivyConfigurations ((org.ensime.EnsimePlugin) EnsimePlugin.scala:101)
[info] [error]      Did you mean *:ivyConfigurations ?
```

**Comment by dwijnand** [comment]
Here's a (deprecated method) hack to fetch artefacts: https://github.com/typesafehub/migration-manager/blob/b34b2b9bc8e60fd7bfe4f622214a6535358f4a6c/sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala#L108

It's deprecated so.. caveat emptor

**Comment by fommil** [comment]
#260 should make this trivial, I hope
